# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Nugets

on:
  release: 
    types: [published]
  workflow_dispatch:

jobs:  
  job:
    name: Build & Release
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Configure Github Nuget repository
        run: dotnet nuget add source --username ismailbennani --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Dofus-Batteries-Included/index.json"

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release --no-build --output nuget/

      - name: Publish nugets
        if: ${{ github.event_name == 'release' }}
        run: |
          foreach($File in (Get-ChildItem "nuget/" -Recurse -Include *.nupkg)) {
              dotnet nuget push $File --source github --api-key ${{ secrets.GITHUB_TOKEN }}
          }

      - name: Upload nugets to artifacts
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: nugets
          path: nuget/*.nupkg
          if-no-files-found: 'error'

permissions:
  contents: write
  packages: write